### ISSUE TITLE
Website is expired

### ISSUE THREAD

**Issue by tebjan** [s-oram/Grace#1]
http://onesmallclue.com/

so the binaries cannot be downloaded anymore. maybe consider a GitHub release?

**Comment by tebjan** [comment]
for now this seems to work: http://web.archive.org/web/20170809154620/http://www.onesmallclue.com:80/plugin/grace/

**Comment by s-oram** [comment]
Thanks Tebjan, I've just renewed the domain. The website should come back online soon.
